# Generated by Django 4.1.7 on 2023-03-03 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128)),
                ('slug', models.CharField(blank=True, max_length=128, null=True, unique=True)),
                ('sponsor_type', models.CharField(choices=[('individual', 'Individual'), ('entity', 'Entity')], default='individual', max_length=100)),
                ('phone_number', models.CharField(max_length=128)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('company_name', models.CharField(blank=True, max_length=128, null=True)),
                ('register_datetime', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('yangi', 'New'), ('moderatsiyada', 'In Moderation'), ('tasdiglangan', 'Confirmed'), ('bekor qilingan', 'Canceled')], default='yangi', max_length=100)),
                ('spent_amount', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('payment_type', models.CharField(choices=[('uzcard', 'Uzcard'), ('humo', 'Humo'), ('visa', 'Visa'), ('cash', 'Cash')], default='uzcard', max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128)),
                ('slug', models.CharField(blank=True, max_length=128, null=True, unique=True)),
                ('student_type', models.CharField(choices=[('bakalavr', 'Bachelor'), ('magistr', 'Masters')], max_length=100)),
                ('received_amount', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('tuition_fee', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('phone_number', models.CharField(max_length=128)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128)),
                ('slug', models.CharField(blank=True, max_length=128, null=True, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StudentSponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('sponsor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='metsenat.sponsor')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sponsors', to='metsenat.student')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='student',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='metsenat.university'),
        ),
    ]
